# Generated by Django 5.1.7 on 2025-04-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+20', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='has_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
