# Generated by Django 5.1.7 on 2025-03-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_brand_remove_carlisting_seller_listing_listingimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(),
        ),
    ]
