# Generated by Django 4.2.3 on 2025-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_location_listing_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_on_page', models.CharField(choices=[('top_banner', 'Top Banner'), ('sidebar', 'Sidebar'), ('inline', 'Inline (Every 5th Listing)')], max_length=50)),
                ('ad_network_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
