# Generated by Django 5.1.7 on 2025-03-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_adspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
