# Generated by Django 5.1.7 on 2025-03-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=20),
            preserve_default=False,
        ),
    ]
