# Generated by Django 5.1.7 on 2025-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Electric', 'Electric')], default='Gas', max_length=20),
        ),
    ]
