# Generated by Django 5.1.7 on 2025-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
