# Generated by Django 5.1.7 on 2025-04-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_multiple_reports',
            field=models.BooleanField(default=False),
        ),
    ]
