# Generated by Django 5.1.7 on 2025-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(choices=[('Gas', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Natural Gas', 'Natural Gas')], default='Gas', max_length=20),
        ),
    ]
